# LAB TEST 2022/2023

### Duration: 2 hours

Instructions:
1. You can only refer to lecture notes.
2. Save this file as your _MatricNo_.
3. File should be saved as _.ipynb_ file.
4. Submission will be done after the test ended. Please upload the file in the designated folder in the e-learning. The access to the e-learning will only be closed 5 minutes after the test ended.

_Please run below code to import Numpy and pandas_

In [1]:
import numpy as np
import pandas as pd

## QUESTION 1 [10 MARKS]


Given numbers = [2,4,6,8,10,12]

(i) Find the average of the numbers, $\bar{x}$.

(ii) Then write a program that computes

$$s = \sqrt{\frac{1}{N-1} \sum_{i=1}^N (x_i - \overline{x})^2}$$

Use only Python basics (NumPy or pandas are not allowed).

In [100]:
# WRITE YOUR CODE HERE
numbers = [2,4,6,8,10,12]
avg = sum(numbers)/len(numbers)
print(avg)

def maths(num):
    return ((1/len(numbers)-1)*((num-avg)**2))**(1/2)

nums = []

for i in numbers:
    nums.append(maths(i))
    
print(nums)


7.0
[(2.7948611536229324e-16+4.564354645876384j), (1.6769166921737594e-16+2.7386127875258306j), (5.589722307245865e-17+0.9128709291752769j), (5.589722307245865e-17+0.9128709291752769j), (1.6769166921737594e-16+2.7386127875258306j), (2.7948611536229324e-16+4.564354645876384j)]


## QUESTION 2 [10 MARKS]

Write a function named `Weather` to performs these tasks

(i)&emsp;read temperature in centigrade, $C$ <br>
(ii)&emsp;display the temperature in fahrenheit, $F$ (formula to convert: $F = (C*1.8) + 32$) <br>
(iii)&emsp;create a nested conditional logic to display suitable message according to temperature state below:

    Temperature < 32 then Freezing
    Temperature 32-50 then Very Cold
    Temperature 51-68 then Cold
    Temperature 69-86 then Normal
    Temperature 87-104 then Hot
    Temperature >=105 then Very Hot


In [76]:
# WRITE YOUR CODE HERE
def Weather(cels):
    msg=''
    fah = (cels*1.8)+32
    m1 = 'Temperature in Fahrenheit is: {:.2f}'.format(fah)
    if fah < 32:
        msg = 'The weather is Freezing'
    elif fah <= 50:
        msg = 'The weather is Very Cold'
    elif fah <= 68:
        msg = 'The weather is Cold'
    elif fah <= 86:
        msg = 'The weather is Normal'
    elif fah <= 104:
        msg = 'The weather is Hot'
    else:
        msg = 'The weather is Very Hot'
    
    return m1 +'\n'+ msg
    

Test your function with these values. The output should be as below:

<br>
<img src="Output1.png", style="width: 250px", align="left";>

In [77]:
print(Weather(-10))
print(Weather(0))
print(Weather(15))
print(Weather(24))
print(Weather(37))
print(Weather(50))

Temperature in Fahrenheit is: 14.00
The weather is Freezing
Temperature in Fahrenheit is: 32.00
The weather is Very Cold
Temperature in Fahrenheit is: 59.00
The weather is Cold
Temperature in Fahrenheit is: 75.20
The weather is Normal
Temperature in Fahrenheit is: 98.60
The weather is Hot
Temperature in Fahrenheit is: 122.00
The weather is Very Hot


## QUESTION 3 [10 MARKS]

(i) Create a NumPy array like below:

<br>
<img src="Output2.png", style="width: 200px", align="left";>

In [31]:
# WRITE YOUR CODE HERE
arr = np.array([[33,22,11],[55,66,44],[99,88,77]])
arr

array([[33, 22, 11],
       [55, 66, 44],
       [99, 88, 77]])

(ii) Sort the array given in ascending order.

In [38]:
# WRITE YOUR CODE HERE
arr.sort()
arr

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

(iii) Compute sum of all elements, sum of each column and sum of each row of the sorted array.

In [91]:
# WRITE YOUR CODE HERE
all_e = arr.sum().sum()
col = arr.sum(axis = 0)
row = arr.sum(axis = 1)
print(all_e, col, row)


495 [132 165 198] [ 66 165 264]


(iv) Compute mean of all elements, mean of each column and mean of each row of the sorted array.



In [42]:
# WRITE YOUR CODE HERE
all_m = arr.mean()
col_m = arr.mean(axis = 0)
row_m =arr.mean(axis =1)

print(all_m,col_m, row_m)


55.0 [44. 55. 66.] [22. 55. 88.]


(v) Compute cummulative sum of each column and cummulative product of each row of the given array.


In [99]:
# WRITE YOUR CODE HERE
c_sum  = arr.cumsum()
c_prod = arr.cumprod()

print(c_sum)
print(c_prod)


[ 11  33  66 110 165 231 308 396 495]
[        11        242       7986     351384   19326120 1275523920
 -568905968 1475882368   83466368]


## QUESTION 4 [20 MARKS]
For this question, you are using Automobile Dataset. 

(i) Load the dataset into pandas dataframe.

In [46]:
# WRITE YOUR CODE HERE
df = pd.read_csv('Automobile Dataset.csv')
df


index      company   body-style  wheel-base  length engine-type  \
0       0  alfa-romero  convertible        88.6   168.8        dohc   
1       1  alfa-romero  convertible        88.6   168.8        dohc   
2       2  alfa-romero    hatchback        94.5   171.2        ohcv   
3       3         audi        sedan        99.8   176.6         ohc   
4       4         audi        sedan        99.4   176.6         ohc   
..    ...          ...          ...         ...     ...         ...   
56     81   volkswagen        sedan        97.3   171.7         ohc   
57     82   volkswagen        sedan        97.3   171.7         ohc   
58     86   volkswagen        sedan        97.3   171.7         ohc   
59     87        volvo        sedan       104.3   188.8         ohc   
60     88        volvo        wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
0              four         111               21  13495.0  
1              four         111               21  16500.0  
2               six         154               19  16500.0  
3              four         102               24  13950.0  
4              five         115               18  17450.0  
..              ...         ...              ...      ...  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0  

[61 rows x 10 columns]

(ii) Display the first and last 5 rows.

In [47]:
# WRITE YOUR CODE HERE (for the first 5 rows)
df.head(5)


index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   
3      3         audi        sedan        99.8   176.6         ohc   
4      4         audi        sedan        99.4   176.6         ohc   

  num-of-cylinders  horsepower  average-mileage    price  
0             four         111               21  13495.0  
1             four         111               21  16500.0  
2              six         154               19  16500.0  
3             four         102               24  13950.0  
4             five         115               18  17450.0

In [50]:
# WRITE YOUR CODE HERE (for the last 5 rows)
df.tail(5)


index     company body-style  wheel-base  length engine-type  \
56     81  volkswagen      sedan        97.3   171.7         ohc   
57     82  volkswagen      sedan        97.3   171.7         ohc   
58     86  volkswagen      sedan        97.3   171.7         ohc   
59     87       volvo      sedan       104.3   188.8         ohc   
60     88       volvo      wagon       104.3   188.8         ohc   

   num-of-cylinders  horsepower  average-mileage    price  
56             four          85               27   7975.0  
57             four          52               37   7995.0  
58             four         100               26   9995.0  
59             four         114               23  12940.0  
60             four         114               23  13415.0

(iii) Print most expensive car’s company name and price.

In [58]:
# WRITE YOUR CODE HERE
m = df['price'].idxmax()
df['company'][m] , df['price'][m]


45400.0


('mercedes-benz', 45400.0)

(iv) Count total cars per company.

In [60]:
# WRITE YOUR CODE HERE
res = df.groupby('company').apply(lambda x: len(x['company'])).reset_index(name= 'Count')
res


company  Count
0     alfa-romero      3
1            audi      4
2             bmw      6
3       chevrolet      3
4           dodge      2
5           honda      3
6           isuzu      3
7          jaguar      3
8           mazda      5
9   mercedes-benz      4
10     mitsubishi      4
11         nissan      5
12        porsche      3
13         toyota      7
14     volkswagen      4
15          volvo      2

(v) Select only Toyota's cars. Find the average mileage and price of Toyota's cars.

In [68]:
# WRITE YOUR CODE HERE
df.loc[df['company'] == 'toyota', ['average-mileage', 'price']]

average-mileage    price
48               35   5348.0
49               31   6338.0
50               31   6488.0
51               31   6918.0
52               27   7898.0
53               27   8778.0
54               19  15750.0

(vi) Sort all cars by Price and Horsepower column. List the expensive cars first.

In [71]:
# WRITE YOUR CODE HERE
df2 = df.sort_values(['price', 'horsepower'],ascending = [False, True])
df2

index        company   body-style  wheel-base  length engine-type  \
35     47  mercedes-benz      hardtop       112.0   199.2        ohcv   
11     14            bmw        sedan       103.5   193.8         ohc   
34     46  mercedes-benz        sedan       120.9   208.1        ohcv   
46     62        porsche  convertible        89.5   168.9        ohcf   
12     15            bmw        sedan       110.0   197.0         ohc   
..    ...            ...          ...         ...     ...         ...   
27     36          mazda    hatchback        93.1   159.1         ohc   
13     16      chevrolet    hatchback        88.4   141.1           l   
22     31          isuzu        sedan        94.5   155.9         ohc   
23     32          isuzu        sedan        94.5   155.9         ohc   
47     63        porsche    hatchback        98.4   175.7       dohcv   

   num-of-cylinders  horsepower  average-mileage    price  
35            eight         184               14  45400.0  
11              six         182               16  41315.0  
34            eight         184               14  40960.0  
46              six         207               17  37028.0  
12              six         182               15  36880.0  
..              ...         ...              ...      ...  
27             four          68               30   5195.0  
13            three          48               47   5151.0  
22             four          70               38      NaN  
23             four          70               38      NaN  
47            eight         288               17      NaN  

[61 rows x 10 columns]

(vii) Display all the maximum car price for each company.

In [95]:
# WRITE YOUR CODE HERE
res2 = df.groupby('company').apply(lambda x: x['price'].max()).reset_index(name= 'Price')
res2

company    Price
0     alfa-romero  16500.0
1            audi  18920.0
2             bmw  41315.0
3       chevrolet   6575.0
4           dodge   6377.0
5           honda  12945.0
6           isuzu   6785.0
7          jaguar  36000.0
8           mazda  18344.0
9   mercedes-benz  45400.0
10     mitsubishi   8189.0
11         nissan  13499.0
12        porsche  37028.0
13         toyota  15750.0
14     volkswagen   9995.0
15          volvo  13415.0

# END OF LAB TEST